insert into ADDRESSES (id, address_line1, address_line2, city, postal_code) values (1, 'Ul. Krucza', '11', 'Poznan', '62-030');
INSERT INTO ADDRESSES (ID, ADDRESS_LINE1, ADDRESS_LINE2, CITY, POSTAL_CODE) VALUES (2, 'Ul. Piekna', '1', 'Warszawa', '01-001');
INSERT INTO ADDRESSES (ID, ADDRESS_LINE1, ADDRESS_LINE2, CITY, POSTAL_CODE) VALUES (3, 'Ul. Morska', '22', 'Warszawa', '01-002');
INSERT INTO ADDRESSES (ID, ADDRESS_LINE1, ADDRESS_LINE2, CITY, POSTAL_CODE) VALUES (4, 'Ul. Dzika', '333', 'Warszawa', '01-003');

INSERT INTO DOCTORS(ID, DOCTOR_NUMBER, EMAIL, FIRST_NAME, LAST_NAME, SPECIALIZATION, TELEPHONE_NUMBER, ADDRESS_ID)
    VALUES (1, '123', 'jkowalski@email.com', 'Jan', 'Kowalski', 'SURGEON', '123456789', 1);
INSERT INTO DOCTORS(ID, DOCTOR_NUMBER, EMAIL, FIRST_NAME, LAST_NAME, SPECIALIZATION, TELEPHONE_NUMBER, ADDRESS_ID)
    VALUES (2, '124', 'amickiewicz@email.com', 'Adam', 'Mickiewicz', 'DERMATOLOGIST', '987654321', 2);

INSERT INTO PATIENTS(ID, DATE_OF_BIRTH, EMAIL, FIRST_NAME, LAST_NAME, PATIENT_NUMBER, TELEPHONE_NUMBER, ADDRESS_ID)
    VALUES (1, '1990-01-01', 'mnowak@mail.com', 'Marek', 'Nowak', '123', '123456789', 3);
INSERT INTO PATIENTS(ID, DATE_OF_BIRTH, EMAIL, FIRST_NAME, LAST_NAME, PATIENT_NUMBER, TELEPHONE_NUMBER, ADDRESS_ID)
    VALUES (2, '1991-02-02', 'kkajak@mail.com', 'Kamil', 'Kajak', '124', '987654321', 4);

INSERT INTO VISITS(ID, DESCRIPTION, TIME, PATIENT_ID, DOCTOR_ID)
    VALUES (1, 'First visit', '2020-01-01 10:00:00', 1, 1);
INSERT INTO VISITS(ID, DESCRIPTION, TIME, PATIENT_ID, DOCTOR_ID)
    VALUES (2, 'Second visit', '2020-02-02 11:00:00', 2, 2);

INSERT INTO MEDICAL_TREATMENTS(ID, DESCRIPTION, TYPE, VISIT_ID)
    VALUES (1, 'Surgery', 'RTG', 1);
INSERT INTO MEDICAL_TREATMENTS(ID, DESCRIPTION, TYPE, VISIT_ID)
    VALUES (2, 'Dermatological examination', 'USG', 2);